"use client";
import { FormEvent, useState } from "react";

export function AndrosHeader() { const [open,setOpen]=useState(false); return <header className="ag-header"><div className="ag-shell ag-header-inner"><a className="ag-logo" href="#top"><span>ANDROS</span><small>GEAR MANUFACTURERS</small></a><button className="ag-menu" type="button" aria-expanded={open} aria-controls="ag-nav" onClick={()=>setOpen(!open)}><i/><i/><span>Menu</span></button><nav id="ag-nav" className={open?"is-open":""}>{[['Capabilities','#capabilities'],['Products','#products'],['Industries','#industries'],['Quality','#quality'],['About','#about'],['Contact','#contact']].map(([label,href])=><a key={label} href={href} onClick={()=>setOpen(false)}>{label}</a>)}<a className="ag-header-cta" href="#rfq" onClick={()=>setOpen(false)}>Request a quote</a></nav></div></header>; }

const types = ["New gear / component", "CNC machining", "Gearbox repair", "Reverse engineering", "Other"] as const;
export function AndrosRfq() {
 const [step,setStep]=useState(1),[type,setType]=useState<(typeof types)[number]>(types[0]),[done,setDone]=useState(false);
 function next(){setStep(s=>Math.min(4,s+1))} function back(){setStep(s=>Math.max(1,s-1))} function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setDone(true)}
 return <><form className="ag-rfq" onSubmit={submit}><div className="ag-rfq-progress">{[1,2,3,4].map(n=><button type="button" key={n} className={step===n?"is-active":step>n?"is-done":""} onClick={()=>setStep(n)}><span>0{n}</span>{["Requirement","Details","Files","Contact"][n-1]}</button>)}</div><div className="ag-rfq-panel">
 {step===1&&<fieldset><legend>What do you need?</legend><p>Select the closest starting point. The final workflow could route each request to the appropriate team.</p><div className="ag-type-grid">{types.map(item=><label className={type===item?"is-active":""} key={item}><input type="radio" name="type" checked={type===item} onChange={()=>setType(item)}/><span>{item}</span><b>↗</b></label>)}</div></fieldset>}
 {step===2&&<fieldset><legend>Project details</legend><p>Share the information already available. Technical requirements can be reviewed after submission.</p><div className="ag-form-grid"><label>Quantity<input name="quantity" inputMode="numeric"/></label><label>Material, if known<input name="material"/></label><label>Required date<input type="date" name="date"/></label><label>Part / drawing number<input name="partNumber"/></label></div><label className="ag-full-label">Project description<textarea name="description" rows={5}/></label><label className="ag-check"><input type="checkbox" name="existing"/> An existing component or sample is available</label></fieldset>}
 {step===3&&<fieldset><legend>Drawings & technical files</legend><p>In a production workflow, drawings could be attached securely for technical review.</p><div className="ag-upload"><span>＋</span><strong>Upload drawings or technical files</strong><small>Demonstration only · no file will be selected, uploaded or stored.</small><div>PDF&nbsp;&nbsp; DWG&nbsp;&nbsp; DXF&nbsp;&nbsp; STEP</div></div></fieldset>}
 {step===4&&<fieldset><legend>Contact information</legend><p>Details the team would need to respond to the request.</p><div className="ag-form-grid"><label>Company<input name="company" autoComplete="organization"/></label><label>Contact name<input name="name" autoComplete="name"/></label><label>Email<input type="email" name="email" autoComplete="email"/></label><label>Phone<input type="tel" name="phone" autoComplete="tel"/></label><label>Location<input name="location" autoComplete="address-level2"/></label></div><label className="ag-full-label">Additional notes<textarea name="notes" rows={4}/></label></fieldset>}
 <div className="ag-rfq-actions"><small>No information or files are transmitted or stored.</small><div>{step>1&&<button type="button" className="ag-back" onClick={back}>Back</button>}{step<4?<button type="button" className="ag-next" onClick={next}>Continue <span>→</span></button>:<button type="submit" className="ag-next">Submit RFQ <span>→</span></button>}</div></div></div></form>
 {done&&<div className="ag-modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setDone(false)}}><section className="ag-modal" role="dialog" aria-modal="true" aria-labelledby="ag-modal-title"><button onClick={()=>setDone(false)} aria-label="Close">×</button><span className="ag-kicker">Workflow simulation</span><h2 id="ag-modal-title">RFQ workflow demonstration</h2><p>In a production version, this request could be routed to the appropriate Andros team with the technical information and drawings required for review.</p><button className="ag-btn" onClick={()=>setDone(false)}>Close</button></section></div>}</>;
}
