import type { Metadata } from "next";
import Image from "next/image";
import { DemoDisclaimerBar } from "@/components/demo/demo-disclaimer-bar";
import { DemoFooterDisclaimer } from "@/components/demo/demo-footer-disclaimer";
import { ScrollToTopButton } from "@/components/demo/scroll-to-top-button";
import { androsGears as andros } from "@/config/andros-gears";
import { AndrosHeader, AndrosRfq } from "./andros-client";

export const metadata:Metadata={title:"Andros Gears Concept — Cédric Nampa",description:"Independent concept for the next generation of Andros Gears’ digital experience.",robots:{index:false,follow:false,googleBot:{index:false,follow:false}},openGraph:{title:"Andros Gears Concept — Cédric Nampa",description:"An independent digital modernization concept for Andros Gears.",images:[{url:"/andros-gears/og.svg",width:1200,height:630}]}};
const Arrow=()=> <span aria-hidden="true">↗</span>;

export default function AndrosPage(){return <div className="ag-site" id="top"><DemoDisclaimerBar companyName="Andros Gears" locale="en" detailText="This independent concept was created by Cédric Nampa for demonstration and prospecting purposes. It is not the official Andros Gears website, was not commissioned by Andros, and does not imply collaboration or approval."/><AndrosHeader/><main>
 <section className="ag-hero"><Image src="/andros-gears/parallax.jpg" alt="Industrial gears — image published by Andros Gears" fill priority sizes="100vw"/><div className="ag-hero-grid" aria-hidden="true"/><div className="ag-shell ag-hero-inner"><span className="ag-kicker">Precision gear manufacturing · Laval, Québec</span><h1>Precision engineered.<br/><em>Built for industry.</em></h1><p>Custom gear manufacturing, CNC machining, gearbox repair and reverse engineering — built around your technical requirements.</p><div className="ag-actions"><a className="ag-btn" href="#rfq">Request a quote <Arrow/></a><a className="ag-link" href="#capabilities">Explore capabilities <span>↓</span></a></div><a className="ag-repair-link" href="#repair"><b>Equipment down?</b><span>Discuss gearbox repair</span><Arrow/></a></div><div className="ag-hero-spec"><span>EST.</span><strong>1989</strong><small>ANDROS GEAR<br/>MANUFACTURERS</small></div></section>

 <section className="ag-capabilities" id="capabilities"><div className="ag-shell"><div className="ag-section-head"><div><span className="ag-kicker">Core capabilities</span><h2>Built around<br/>your requirements.</h2></div><p>From a single damaged component to production quantities, the starting point is the same: understand the part, the operating context and the technical requirement.</p></div><div className="ag-cap-grid">{[["01","Gear manufacturing","Custom spur, helical, worm, internal, sprocket, rack and straight bevel gears, with spiral bevel gears also supplied."],["02","CNC machining","CNC lathes and vertical machining centres for prototypes, small lots or larger production requirements."],["03","Gearbox repair","Complete overhaul work including casings, bearings, seals, gaskets, washers and replacement components."],["04","Reverse engineering","A path forward when original drawings are unavailable but an existing or damaged component can be studied."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><a href="#rfq">Start an RFQ <Arrow/></a></article>)}</div></div></section>

 <section className="ag-specs"><div className="ag-shell"><div className="ag-section-head ag-section-head-light"><div><span className="ag-kicker">Published technical data</span><h2>Capabilities<br/>at a glance.</h2></div><p>Dimensions below reproduce the capacity information currently published by Andros. Imperial units are retained exactly as presented.</p></div><div className="ag-spec-layout"><div className="ag-spec-table"><div className="ag-spec-row ag-spec-header"><span>Gear type</span><span>Diameter</span><span>Pitch</span><span>Face / length</span></div>{andros.capabilities.map(row=><div className="ag-spec-row" key={row.type}><strong>{row.type}</strong><span>{row.diameter}</span><span>{row.pitch}</span><span>{row.face}</span></div>)}</div><aside><span className="ag-kicker">Machinery</span>{andros.machinery.map(([name,value])=><div key={name}><strong>{name}</strong><span>{value}</span></div>)}</aside></div></div></section>

 <section className="ag-products" id="products"><div className="ag-shell"><div className="ag-section-head"><div><span className="ag-kicker">Product range</span><h2>What we<br/>manufacture.</h2></div><p>Custom profiles manufactured to customer specifications, supported by internal spline and keyway machining.</p></div><div className="ag-product-layout"><figure><Image src="/andros-gears/panel-1.jpg" alt="Selection of industrial gears published by Andros Gears" fill sizes="(max-width: 800px) 100vw, 45vw"/><figcaption>Actual product imagery published by Andros</figcaption></figure><div className="ag-product-grid">{andros.products.map((item,index)=><a href="#rfq" key={item}><span>0{index+1}</span><strong>{item}</strong><Arrow/></a>)}</div></div></div></section>

 <section className="ag-industries" id="industries"><div className="ag-shell"><span className="ag-kicker">Operating environments</span><h2>Built for demanding industries.</h2><div className="ag-industry-grid">{andros.industries.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><strong>{item}</strong></div>)}</div><p className="ag-data-note">Industries listed by Andros. No customer or contract relationship is implied.</p></div></section>

 <section className="ag-repair" id="repair"><Image src="/andros-gears/panel-2.jpg" alt="Gear component imagery published by Andros" fill sizes="100vw"/><div className="ag-repair-shade"/><div className="ag-shell ag-repair-inner"><span className="ag-kicker">Gearbox repair</span><h2>When downtime<br/>isn’t an option.</h2><p>Andros publishes complete gearbox overhaul capabilities: casing repair and machining, replacement of bearings, seals, gaskets and washers, plus work from original prints or reverse engineering of the assembly.</p><div className="ag-repair-steps">{["Assessment","Casing & components","Reverse engineering","Repair / overhaul"].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div><a className="ag-btn" href="#rfq">Discuss a gearbox repair <Arrow/></a></div></section>

 <section className="ag-quality" id="quality"><div className="ag-shell ag-quality-grid"><div><span className="ag-kicker">Quality assurance</span><h2>Precision<br/>requires control.</h2><p>Andros describes a documented manufacturing process, inspection in a segregated quality-control room, re-verification by an inspector and customer-specific quality plans that can produce a Quality Assurance Report.</p><div className="ag-iso-note"><strong>About ISO 9002</strong><p>The current Andros website references ISO 9002. Because no current certificate could be verified from the published material, this concept does not present Andros as currently ISO certified.</p></div></div><ol><li><span>01</span><strong>Documented process</strong><p>Manufacturing operations are documented and controlled by the employee performing the work.</p></li><li><span>02</span><strong>Dedicated inspection</strong><p>Published inspection equipment is located in a separate quality-control room.</p></li><li><span>03</span><strong>Customer requirements</strong><p>Specific verification areas and frequency can inform a tailored Quality Plan.</p></li><li><span>04</span><strong>Quality reporting</strong><p>The published process can produce a report confirming work against specifications.</p></li></ol></div></section>

 <section className="ag-story" id="about"><div className="ag-shell ag-story-grid"><div className="ag-story-year"><small>ESTABLISHED</small><strong>1989</strong></div><div><span className="ag-kicker">Experience & adaptability</span><h2>Engineering experience since 1989.</h2><p>Andros states that the company was established in 1989 by Andre Andriopoulos with a focus on reliable machining. Today, its published offer combines custom gearing, precision-machined components, gearbox work and investment in manufacturing knowledge.</p><blockquote>“Pride, Quality, Service”</blockquote><p className="ag-quote-note">Company motto published by Andros Gears.</p></div></div></section>

 <section className="ag-workflow"><div className="ag-shell"><div className="ag-section-head"><div><span className="ag-kicker">A clearer customer journey</span><h2>From requirement<br/>to production.</h2></div><p>A concise visualization of how a digital RFQ can prepare the technical conversation. It is not a contractual process or lead-time promise.</p></div><ol>{[["Submit requirements","Need, quantities and available technical context."],["Technical review","The appropriate team reviews the supplied information."],["Quote","Scope, pricing and delivery details can be clarified."],["Production / service","Work can proceed once requirements are agreed."]].map(([t,d],i)=><li key={t}><span>0{i+1}</span><strong>{t}</strong><p>{d}</p></li>)}</ol></div></section>

 <section className="ag-rfq-section" id="rfq"><div className="ag-shell"><div className="ag-section-head ag-section-head-light"><div><span className="ag-kicker">Structured request for quote</span><h2>Start with the<br/>technical need.</h2></div><p>A progressive RFQ reduces the initial form burden while gathering the right context for review.</p></div><AndrosRfq/></div></section>

 <section className="ag-future"><div className="ag-shell"><span className="ag-kicker">Future digital opportunities</span><h2>Beyond the website.</h2><div className="ag-future-grid">{["Smarter RFQ routing","Drawing management","Quote tracking","Repeat-order workflows","Customer portal","Internal system integration"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>A potential future capability — not presented as an existing Andros system.</p></article>)}</div></div></section>

 <section className="ag-contact" id="contact"><div className="ag-shell ag-contact-grid"><div><span className="ag-kicker">Discuss a requirement</span><h2>Have a part,<br/>drawing or repair?</h2><div className="ag-actions"><a className="ag-btn" href="#rfq">Request a quote <Arrow/></a><a className="ag-link" href={andros.phone.href}>{andros.phone.display}</a></div></div><address><strong>Andros Gear Manufacturers</strong><a href={andros.address.directions}>{andros.address.line1}<br/>{andros.address.line2}</a><a href={andros.phone.href}>{andros.phone.display}</a><a href={`mailto:${andros.email}`}>{andros.email}</a></address></div></section>
 </main><footer className="ag-footer"><div className="ag-shell"><div className="ag-footer-grid"><div className="ag-footer-logo"><span>ANDROS</span><small>GEAR MANUFACTURERS</small></div><div><strong>Capabilities</strong><a href="#capabilities">Gear manufacturing</a><a href="#capabilities">CNC machining</a><a href="#repair">Gearbox repair</a></div><div><strong>Explore</strong><a href="#products">Products</a><a href="#industries">Industries</a><a href="#quality">Quality</a></div><div><strong>Contact</strong><a href="#rfq">Request a quote</a><a href={andros.phone.href}>{andros.phone.display}</a><a href={`mailto:${andros.email}`}>{andros.email}</a></div></div><DemoFooterDisclaimer companyName="Andros Gears"/></div></footer><div className="ag-mobile-cta"><a href={andros.phone.href}>Call</a><a href="#rfq">Request a quote</a></div><ScrollToTopButton/></div>}
