import type { Metadata } from "next";
import Image from "next/image";
import { DemoDisclaimerBar } from "@/components/demo/demo-disclaimer-bar";
import { DemoFooterDisclaimer } from "@/components/demo/demo-footer-disclaimer";
import { ScrollToTopButton } from "@/components/demo/scroll-to-top-button";
import { comptableLaval as business } from "@/config/comptable-laval";
import { LavalContactForm, LavalFaq, LavalHeader } from "./comptable-laval-client";

export const metadata: Metadata = {
  title: "Concept Comptable Laval — Cédric Nampa",
  description: "Proposition indépendante de modernisation de l’expérience numérique de Comptable Laval.",
  robots: { index: false, follow: false, googleBot: { index: false, follow: false } },
  openGraph: { title: "Concept Comptable Laval — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique de Comptable Laval.", images: [{ url: "/comptable-laval/og.svg", width: 1200, height: 630 }] },
};

const Arrow = () => <span aria-hidden="true">→</span>;

export default function ComptableLavalPage() {
  return <div className="cl-site" id="accueil">
    <DemoDisclaimerBar companyName="Comptable Laval / Olga Gorea" detailText="Cette page est un concept indépendant réalisé à des fins de démonstration et de prospection. Elle ne représente pas le site officiel de Comptable Laval ou d’Olga Gorea, n’a pas été commandée par le cabinet et n’implique aucune collaboration ou approbation." />
    <LavalHeader />
    <main>
      <section className="cl-hero">
        <div className="cl-hero-slides" aria-hidden="true"><Image className="cl-hero-slide cl-hero-slide-one" src="/comptable-laval/hero-slide-1.webp" alt="" fill priority sizes="100vw" /><Image className="cl-hero-slide cl-hero-slide-two" src="/comptable-laval/hero-slide-2.webp" alt="" fill priority sizes="100vw" /></div>
        <div className="cl-hero-overlay" aria-hidden="true" />
        <div className="cl-shell cl-hero-grid"><div className="cl-hero-copy"><span className="cl-kicker">Comptabilité · Fiscalité · Accompagnement</span><h1>Votre comptabilité,<br /><em>sans perdre de vue vos projets.</em></h1><p>Des services comptables et fiscaux adaptés aux entreprises, travailleurs autonomes et particuliers de Laval et du Grand Montréal.</p><div className="cl-actions"><a className="cl-button" href="#contact">Parler de mes besoins <Arrow /></a><a className="cl-text-link" href="#services">Découvrir les services <Arrow /></a></div><div className="cl-hero-trust"><span>Olga Gorea, CPA</span><span>Laval & Grand Montréal</span><span>Services personnalisés</span></div></div></div>
        <div className="cl-slide-indicator" aria-hidden="true"><i /><i /></div>
      </section>

      <section className="cl-profile-section" id="profils"><div className="cl-shell"><div className="cl-section-head"><span className="cl-kicker">Un parcours qui commence par vous</span><h2>Comment pouvons-nous vous aider&nbsp;?</h2><p>Choisissez la situation qui vous ressemble. Les services pertinents deviennent tout de suite plus simples à repérer.</p></div><div className="cl-profile-grid">{business.audiences.map((audience, index) => <article className={`cl-profile-card cl-profile-${index + 1}`} key={audience.id}><span className="cl-profile-number">0{index + 1}</span><h3>{audience.title}</h3><p>{audience.description}</p><ul>{audience.items.map(item => <li key={item}>{item}</li>)}</ul><a href="#contact">{index === 0 ? "Services aux entreprises" : index === 1 ? "Services aux travailleurs autonomes" : "Services aux particuliers"} <Arrow /></a></article>)}</div></div></section>

      <section className="cl-startup" id="demarrage"><div className="cl-shell cl-startup-grid"><div><span className="cl-kicker cl-kicker-light">Accompagnement entrepreneurial</span><h2>Vous démarrez<br />votre entreprise&nbsp;?</h2><p>Les premières décisions comptables et fiscales peuvent avoir des conséquences durables. Un accompagnement adapté permet de partir sur de meilleures bases.</p><a className="cl-button cl-button-ivory" href="#contact">Discuter de mon projet <Arrow /></a></div><ol className="cl-startup-steps"><li><span>01</span><div><strong>Démarrage</strong><p>Comprendre les premières obligations.</p></div></li><li><span>02</span><div><strong>Structure</strong><p>Discuter d’une structure appropriée.</p></div></li><li><span>03</span><div><strong>Incorporation</strong><p>Être accompagné lorsque cette option est pertinente.</p></div></li><li><span>04</span><div><strong>Comptabilité</strong><p>Organiser les méthodes et les outils dès le départ.</p></div></li></ol></div></section>

      <section className="cl-services" id="services"><div className="cl-shell"><div className="cl-section-head cl-section-head-row"><div><span className="cl-kicker">L’essentiel, bien organisé</span><h2>Des services plus simples à parcourir.</h2></div><p>Une expertise complète, regroupée selon ce qu’elle vous aide concrètement à accomplir.</p></div><div className="cl-services-grid">{business.serviceGroups.map(group => <article key={group.number}><span>{group.number}</span><h3>{group.title}</h3><p>{group.text}</p><ul>{group.items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

      <section className="cl-digital"><div className="cl-shell cl-digital-grid"><div className="cl-digital-copy"><span className="cl-kicker cl-kicker-light">Comptabilité numérique</span><h2>Une comptabilité adaptée aux outils d’aujourd’hui.</h2><p>Des outils numériques peuvent faciliter l’organisation comptable, le partage d’information et le suivi de votre entreprise.</p><small>Outils mentionnés par Comptable Laval. Aucune certification ou affiliation n’est sous-entendue.</small></div><div className="cl-tools">{business.tools.map((tool, index) => <div key={tool}><span>0{index + 1}</span><strong>{tool}</strong><p>{index === 2 ? "Une organisation plus souple de l’information comptable." : "Un outil connu pour soutenir la gestion comptable."}</p></div>)}</div></div></section>

      <section className="cl-sectors"><div className="cl-shell"><div className="cl-section-head cl-section-head-row"><div><span className="cl-kicker">Des réalités différentes</span><h2>Une comptabilité adaptée à votre terrain.</h2></div><p>Le cabinet présente une expérience auprès d’entreprises issues de plusieurs secteurs d’activité.</p></div><div className="cl-sector-grid">{business.sectors.map((sector, index) => <div key={sector}><span aria-hidden="true">{["⌂","▦","◇","◎"][index]}</span><strong>{sector}</strong></div>)}</div></div></section>

      <section className="cl-confidence"><div className="cl-shell cl-confidence-grid"><div><span className="cl-kicker">Une relation de proximité</span><h2>Des chiffres clairs pour prendre de meilleures décisions.</h2></div><div className="cl-benefits"><article><strong>Accompagnement personnalisé</strong><p>Une approche qui tient compte de votre situation et de votre organisation.</p></article><article><strong>Une expertise orientée PME</strong><p>Des services comptables, fiscaux et de gestion réunis.</p></article><article><strong>Travailleurs autonomes</strong><p>Une offre adaptée aux obligations propres au travail indépendant.</p></article><article><strong>Comptabilité et fiscalité</strong><p>Une lecture plus cohérente de deux dimensions étroitement liées.</p></article></div></div></section>

      <section className="cl-process"><div className="cl-shell"><div className="cl-section-head"><span className="cl-kicker">Une expérience plus lisible</span><h2>Un accompagnement sans complication.</h2></div><ol>{[["Présentez votre situation","Expliquez-nous simplement où vous en êtes."],["Identifions vos besoins","Repérons les services qui correspondent à votre réalité."],["Mise en place","Organisons les services et les prochaines étapes appropriées."],["Suivi","Maintenons une information claire au fil de l’accompagnement."]].map(([title,text], index) => <li key={title}><span>0{index + 1}</span><strong>{title}</strong><p>{text}</p></li>)}</ol></div></section>

      <section className="cl-about" id="a-propos"><div className="cl-shell cl-about-grid"><div className="cl-about-photo"><Image src="/comptable-laval/olga.png" alt="Olga Gorea, CPA" fill sizes="(max-width: 800px) 100vw, 40vw" /></div><div><span className="cl-kicker">À propos</span><h2>Une professionnelle accessible derrière les chiffres.</h2><p>Olga Gorea, CPA, offre des services de comptabilité, de fiscalité et de consultation à une clientèle d’entreprises, de travailleurs autonomes et de particuliers.</p><p>Son parcours public mentionne une formation en gestion, cheminement comptabilité, à HEC Montréal, ainsi que le programme professionnel CGA à l’Université de Sherbrooke. Elle est membre de l’Ordre des CPA du Québec.</p><a className="cl-text-link" href="#contact">Échanger avec le cabinet <Arrow /></a></div></div></section>

      <section className="cl-future"><div className="cl-shell"><div className="cl-section-head"><span className="cl-kicker cl-kicker-light">Possibilités d’évolution</span><h2>Une expérience client qui peut aller plus loin.</h2><p>Une modernisation progressive pourrait relier le site aux outils qui simplifient réellement la relation avec le cabinet.</p></div><div className="cl-future-grid">{[["Prise de rendez-vous","Choisir un moment adapté en ligne."],["Documents sécurisés","Transmettre certains fichiers dans un environnement prévu à cet effet."],["Rappels automatisés","Recevoir les confirmations et rappels utiles."],["Qualification","Diriger la demande selon le profil et le besoin."],["Espace client","Centraliser progressivement les échanges pertinents."]].map(([title,text], index) => <article key={title}><span>Possibilité 0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="cl-contact" id="contact"><div className="cl-shell"><div className="cl-contact-intro"><div><span className="cl-kicker cl-kicker-light">Premier échange</span><h2>Parlez-nous de votre situation.</h2></div><p>Un formulaire qui pose les bonnes questions dès le départ, sans vous demander de connaître le jargon comptable.</p></div><LavalContactForm /></div></section>

      <section className="cl-faq"><div className="cl-shell cl-faq-grid"><div><span className="cl-kicker">Questions fréquentes</span><h2>Avant de prendre contact.</h2><p>Des réponses courtes pour vous orienter vers le bon service.</p></div><LavalFaq /></div></section>

      <section className="cl-final"><div className="cl-shell cl-final-inner"><div><span className="cl-kicker cl-kicker-light">Commençons simplement</span><h2>Votre situation mérite plus qu’une réponse générique.</h2><p>Parlez-nous de vos besoins comptables ou fiscaux et commencez par identifier le service qui vous convient.</p></div><div className="cl-actions"><a className="cl-button cl-button-ivory" href="#contact">Parler de mes besoins <Arrow /></a><a className="cl-final-phone" href={business.phone.href}>{business.phone.display}</a></div></div></section>
    </main>
    <footer className="cl-footer"><div className="cl-shell"><div className="cl-footer-grid"><div><strong className="cl-footer-brand">Comptable Laval</strong><span>Olga Gorea, CPA</span><p>Comptabilité · Fiscalité · Accompagnement</p></div><div><strong>Nous joindre</strong><a href={business.phone.href}>{business.phone.display}</a><a href={`mailto:${business.email}`}>{business.email}</a></div><div><strong>Adresse</strong><a href={business.address.directions}>{business.address.line1}<br />{business.address.line2}</a></div><div><strong>Navigation</strong><a href="#profils">Pour qui</a><a href="#services">Services</a><a href="#contact">Contact</a><a href={business.officialWebsite}>Site officiel</a></div></div><DemoFooterDisclaimer companyName="Comptable Laval / Olga Gorea" /></div></footer>
    <ScrollToTopButton />
  </div>;
}
