import type { Metadata } from "next";
import Image from "next/image";
import { DemoDisclaimerBar } from "@/components/demo/demo-disclaimer-bar";
import { DemoFooterDisclaimer } from "@/components/demo/demo-footer-disclaimer";
import { ScrollToTopButton } from "@/components/demo/scroll-to-top-button";
import { salonApresLimage as salon } from "@/config/salon-apres-limage";
import { SalonBooking, SalonHeader } from "./salon-client";

export const metadata: Metadata = { title: "Concept Salon Après l’Image — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique du Salon Après l’Image.", robots: { index: false, follow: false, googleBot: { index: false, follow: false } }, openGraph: { title: "Concept Salon Après l’Image — Cédric Nampa", description: "Une histoire qui traverse les générations. Un concept numérique indépendant et non officiel.", images: [{ url: "/salon-apres-limage/og.svg", width: 1200, height: 630 }] } };

const Arrow = () => <span aria-hidden="true">↗</span>;

export default function SalonPage() {
  return <div className="sa-site" id="accueil"><DemoDisclaimerBar companyName={salon.companyName} detailText="Cette page est un concept indépendant réalisé à des fins de démonstration et de prospection. Elle ne représente pas le site officiel du Salon Après l’Image, n’a pas été commandée par le salon et n’implique aucune collaboration ou approbation." /><SalonHeader /><main>
    <section className="sa-hero"><video className="sa-hero-video" autoPlay muted loop playsInline preload="metadata" poster="/salon-apres-limage/founders.webp" aria-hidden="true" tabIndex={-1}><source src="/salon-apres-limage/hero-background.mp4" type="video/mp4" /></video><div className="sa-hero-shade" /><div className="sa-shell sa-hero-inner"><span className="sa-eyebrow">Coiffure · Barbier · Laval</span><h1>Votre style.<br /><em>Notre histoire</em><br />depuis 1976.</h1><p>Coiffure, barbier et expérience salon pour hommes, femmes et familles, dans une ambiance qui réunit tradition et nouvelle génération.</p><div className="sa-actions"><a className="sa-solid" href="#reservation">Prendre rendez-vous <Arrow /></a><a className="sa-outline" href="#histoire">Découvrir le salon</a></div></div><div className="sa-hero-meta"><span>Depuis 1976</span><span>Hommes · Femmes · Enfants</span><span>Laval</span></div></section>

    <section className="sa-history" id="histoire"><div className="sa-shell"><div className="sa-section-intro"><span className="sa-eyebrow">Une maison de quartier</span><h2>Une histoire<br /><em>de générations.</em></h2></div><div className="sa-history-grid"><div className="sa-history-copy"><div className="sa-date"><strong>1976</strong><span>→ aujourd’hui</span></div><p>Né comme un barbier, le Salon Après l’Image continue de faire vivre cette tradition tout en accueillant les styles, les clientèles et les façons de faire d’une nouvelle génération.</p><p>Au fil du temps, l’offre s’est ouverte aux hommes, aux femmes, aux enfants et aux familles — sans perdre l’esprit chaleureux qui définit le salon.</p></div><figure className="sa-history-photo sa-old"><Image src="/salon-apres-limage/founders.webp" alt="Les fondateurs du Salon Après l’Image" fill sizes="(max-width: 800px) 100vw, 45vw" /><figcaption>Les fondateurs</figcaption></figure><figure className="sa-history-photo sa-new"><Image src="/salon-apres-limage/new-generation.webp" alt="La nouvelle génération du Salon Après l’Image" fill sizes="(max-width: 800px) 100vw, 45vw" /><figcaption>La nouvelle génération</figcaption></figure></div></div></section>

    <section className="sa-services" id="services"><div className="sa-shell"><div className="sa-section-intro sa-section-intro-light"><span className="sa-eyebrow">Un salon pour tous les styles</span><h2>Quel style<br />recherchez-vous&nbsp;?</h2></div><div className="sa-service-grid">{Object.entries(salon.services).map(([key, items], index) => <article key={key}><span className="sa-service-index">0{index + 1}</span><h3>{key === "homme" ? "Homme" : key === "femme" ? "Femme" : "Enfants & famille"}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><a href="#reservation">Découvrir les services <Arrow /></a></article>)}</div><p className="sa-price-note">Les prix affichés sur le site actuel étant contradictoires, ils ne sont pas reproduits dans ce concept. Les tarifs peuvent varier selon le service, la longueur des cheveux et le professionnel; ils sont à confirmer au moment du rendez-vous.</p></div></section>

    <section className="sa-visit" id="visite"><div className="sa-shell sa-visit-grid"><div className="sa-visit-image"><Image src="/salon-apres-limage/new-generation.webp" alt="Nouvelle génération du Salon Après l’Image devant le salon" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div><span className="sa-eyebrow">Votre visite</span><h2>Plus qu’un rendez-vous chez le coiffeur.</h2><p>Chez Après l’Image, la coiffure est aussi une histoire de rencontre. Le salon réunit le geste professionnel, l’ambiance d’un lieu de quartier et quelques attentions qui rendent la visite plus agréable.</p><div className="sa-visit-list"><div><span>01</span><strong>Coiffure & style</strong></div><div><span>02</span><strong>Barbier</strong></div><div><span>03</span><strong>Café-Bar</strong></div><div><span>04</span><strong>Wi-Fi & ambiance</strong></div></div></div></div></section>

    <section className="sa-creations" id="creations"><div className="sa-shell"><div className="sa-creations-head"><div><span className="sa-eyebrow">Médias du salon</span><h2>Le style,<br /><em>à votre image.</em></h2></div><p>Les créations existantes méritent un espace qui les laisse respirer. Voici comment les véritables vidéos du salon pourraient devenir une galerie vivante.</p></div><div className="sa-video-grid">{salon.videos.map((video, index) => <figure key={video.title} className={index === 0 ? "sa-video-featured" : ""}><video controls preload="metadata" playsInline><source src={video.src} type="video/mp4" /></video><figcaption><span>Film 0{index + 1}</span><strong>{video.title}</strong></figcaption></figure>)}</div></div></section>

    <section className="sa-social"><div className="sa-shell sa-social-grid"><div><span className="sa-eyebrow">@salonapreslimage</span><h2>Suivez la vie<br />du salon.</h2><p>Nouveaux styles, moments du quotidien et souvenirs de plusieurs générations.</p><a className="sa-solid sa-solid-cream" href={salon.instagram}>Suivre sur Instagram <Arrow /></a></div><div className="sa-social-collage"><div><Image src="/salon-apres-limage/founders.webp" alt="Les fondateurs du salon" fill sizes="40vw" /></div><div><Image src="/salon-apres-limage/new-generation.webp" alt="La nouvelle génération du salon" fill sizes="40vw" /></div><span>1976<br />—<br />2026</span></div></div></section>

    <section className="sa-event"><div className="sa-shell sa-event-inner"><span>Occasions spéciales</span><h2>Un événement<br /><em>à votre image&nbsp;?</em></h2><p>Mariage, fête ou occasion particulière : discutez de votre style et de vos besoins avec l’équipe.</p><a className="sa-outline sa-outline-dark" href="#reservation">Parler de mon événement <Arrow /></a></div></section>

    <section className="sa-reservation" id="reservation"><div className="sa-shell"><div className="sa-reservation-head"><div><span className="sa-eyebrow">Concept de réservation</span><h2>Réservez votre<br />prochain rendez-vous.</h2></div><p>Un parcours simple qui permet au salon de comprendre le service recherché avant même le premier échange.</p></div><SalonBooking /></div></section>

    <section className="sa-future"><div className="sa-shell"><div className="sa-section-intro"><span className="sa-eyebrow">Possibilités futures</span><h2>L’expérience salon<br />peut aussi évoluer en ligne.</h2></div><div className="sa-future-grid">{["Réservation en ligne","Rappels automatiques","Présentation des stylistes","Galerie de réalisations","Cartes-cadeaux"].map((item,index) => <article key={item}><span>0{index+1}</span><h3>{item}</h3><p>Une possibilité d’évolution à intégrer progressivement dans une version future.</p></article>)}</div></div></section>

    <section className="sa-final" id="contact"><div className="sa-shell sa-final-grid"><div><span className="sa-eyebrow">628, rue Principale · Laval</span><h2>Votre prochain style<br /><em>commence ici.</em></h2><p>Coupe, barbe, couleur ou simplement envie de changement : prenez le temps de trouver un style qui vous ressemble.</p></div><div className="sa-contact-card"><strong>{salon.hours}</strong><p>Contactez le salon pour connaître les disponibilités. Les numéros publiés actuellement étant contradictoires, aucun numéro n’est repris dans ce concept.</p><a className="sa-solid" href="#reservation">Prendre rendez-vous <Arrow /></a><a href={salon.address.directions}>Voir l’itinéraire</a></div></div></section>
  </main><footer className="sa-footer"><div className="sa-shell"><div className="sa-footer-grid"><div className="sa-footer-brand"><span>APRÈS</span><i>L’IMAGE</i><small>Coiffure · Barbier · Café-Bar</small></div><div><strong>Le salon</strong><p>{salon.address.line1}<br />{salon.address.line2}</p><p>{salon.hours}</p></div><div><strong>Nous suivre</strong><a href={salon.instagram}>Instagram</a><a href={salon.facebook}>Facebook</a><a href={salon.officialWebsite}>Site officiel</a></div><div><strong>Explorer</strong><a href="#histoire">Notre histoire</a><a href="#services">Services</a><a href="#reservation">Rendez-vous</a></div></div><DemoFooterDisclaimer companyName={salon.companyName} /></div></footer><div className="sa-mobile-cta"><a href="#contact">Contacter</a><a href="#reservation">Rendez-vous</a></div><ScrollToTopButton /></div>;
}
