import type { Metadata } from "next";
import Image from "next/image";
import { DemoDisclaimerBar } from "@/components/demo/demo-disclaimer-bar";
import { DemoFooterDisclaimer } from "@/components/demo/demo-footer-disclaimer";
import { ScrollToTopButton } from "@/components/demo/scroll-to-top-button";
import { jtpv } from "@/config/jtpv";
import { EstimateForm, JtpvMobileCta, JtpvMobileMenu } from "./jtpv-client";

export const metadata: Metadata = {
  title: "Concept JTPV — Cédric Nampa",
  description: "Proposition indépendante de modernisation de l’expérience numérique d’Entreprises d’Électricité J T P V Inc.",
  robots: { index: false, follow: false, nocache: true, googleBot: { index: false, follow: false, noimageindex: true } },
  openGraph: { title: "Concept JTPV — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique d’Entreprises d’Électricité J T P V Inc.", url: "https://demo.cedricnampa.com/jtpv", siteName: "Démonstrations Cédric Nampa", locale: "fr_CA", type: "website", images: [{ url: "/jtpv/og.svg", width: 1200, height: 630, alt: "Concept non officiel de modernisation numérique pour JTPV" }] },
  twitter: { card: "summary_large_image", title: "Concept JTPV — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique de JTPV.", images: ["/jtpv/og.svg"] },
};

const process = [["01", "Présentez votre projet", "Décrivez le contexte, le type de bâtiment et les travaux envisagés."], ["02", "Analyse du besoin", "Les informations transmises permettent de mieux comprendre la nature de la demande."], ["03", "Estimation", "JTPV peut ensuite communiquer avec vous afin d’évaluer les travaux nécessaires."], ["04", "Planification et réalisation", "Les prochaines étapes peuvent être organisées selon la nature du projet."]];
const digital = [["01", "Qualification automatique", "Distinguer immédiatement les demandes résidentielles, commerciales, industrielles et urgentes."], ["02", "Photos et plans", "Permettre la transmission sécurisée de documents utiles avant l’estimation."], ["03", "Routage des demandes", "Acheminer chaque demande au bon interlocuteur selon le type de projet."], ["04", "Suivi automatisé", "Confirmer la réception et faciliter les rappels liés à la demande."]];

export default function JtpvPage() {
  return <div className="jtpv-site">
    <DemoDisclaimerBar companyName={jtpv.companyName} detailText="Cette page est un concept indépendant réalisé à des fins de démonstration et de prospection. Elle ne représente pas le site officiel de JTPV, n’a pas été commandée par l’entreprise et n’implique aucune collaboration ou approbation de sa part." />
    <a className="jtpv-skip" href="#jtpv-content">Aller au contenu</a>
    <header className="jtpv-header"><div className="jtpv-shell jtpv-header-inner"><a className="jtpv-brand" href="#accueil" aria-label="JTPV — accueil"><Image src={jtpv.logo.src} alt={jtpv.logo.alt} width={185} height={48} priority /></a><nav className="jtpv-desktop-nav" aria-label="Navigation principale"><a href="#accueil">Accueil</a><a href="#residentiel">Résidentiel</a><a href="#commercial">Commercial</a><a href="#industriel">Industriel</a><a href="#realisations">Réalisations</a><a href="#a-propos">À propos</a><a href="#estimation">Contact</a></nav><div className="jtpv-header-contact"><span>Urgence 24 h</span><a href={jtpv.phone.href}>{jtpv.phone.display}</a></div><a className="jtpv-button jtpv-header-cta" href="#estimation">Demander une estimation</a><JtpvMobileMenu /></div></header>

    <main id="jtpv-content">
      <section className="jtpv-hero" id="accueil"><div className="jtpv-hero-photo"><Image src="/jtpv/hero-electrician.jpg" alt="Électricien vérifiant les connexions d’un tableau électrique professionnel" fill priority sizes="100vw" /></div><div className="jtpv-hero-overlay" /><div className="jtpv-shell jtpv-hero-content"><p className="jtpv-eyebrow light"><span /> Maître électricien à Montréal</p><h1>L’expertise électrique<br />au service de <em>vos projets.</em></h1><p>Services électriques résidentiels, commerciaux et industriels dans le Grand Montréal, sur la Rive-Nord et la Rive-Sud.</p><div className="jtpv-actions"><a className="jtpv-button jtpv-button-yellow" href="#estimation">Demander une estimation <span aria-hidden="true">↗</span></a><a className="jtpv-link-light" href="#projets">Voir nos services <span aria-hidden="true">↓</span></a><a className="jtpv-urgent-link" href={jtpv.phone.href}><span>Urgence 24 h</span><strong>{jtpv.phone.display}</strong></a></div><small>Image d’illustration — ne représente pas une réalisation de JTPV.</small></div><div className="jtpv-shell jtpv-proofbar"><div><strong>Depuis 1994</strong><span>Entrepreneur en électricité</span></div><div><strong>RBQ</strong><span>{jtpv.rbq}</span></div><div><strong>{jtpv.liabilityInsurance}</strong><span>Assurance responsabilité civile</span></div><div><strong>24 h</strong><span>Service d’urgence</span></div></div></section>

      <section className="jtpv-projects" id="projets"><div className="jtpv-shell"><div className="jtpv-heading split"><div><p className="jtpv-eyebrow">Trois marchés, une même exigence</p><h2>Quel type de projet<br /><em>avez-vous?</em></h2></div><p>Un parcours clair permet d’identifier rapidement les services qui correspondent au bâtiment, au contexte et à la nature des travaux.</p></div><div className="jtpv-project-grid">{jtpv.projectTypes.map((project) => <article id={project.id} key={project.id}><figure><Image src={project.image} alt={`Illustration publique d’un contexte ${project.title.toLowerCase()}`} fill sizes="(max-width: 760px) 100vw, 33vw" /><figcaption>Image issue du site public — présentation conceptuelle</figcaption></figure><div><span>{project.number}</span><h3>{project.title}</h3><p>{project.text}</p><a href={project.id === "residentiel" ? "#services-residentiels" : "#services-professionnels"}>Explorer ce parcours <b aria-hidden="true">↗</b></a></div></article>)}</div></div></section>

      <section className="jtpv-residential" id="services-residentiels"><div className="jtpv-shell jtpv-residential-grid"><div className="jtpv-residential-intro"><p className="jtpv-eyebrow light">Services résidentiels</p><h2>Une installation pensée<br />pour votre <em>quotidien.</em></h2><p>Les services suivants sont présentés publiquement par JTPV pour les projets résidentiels.</p><a className="jtpv-button jtpv-button-yellow" href="#estimation">Présenter un projet résidentiel <span aria-hidden="true">↗</span></a></div><ol>{jtpv.residentialServices.map((service, index) => <li key={service}><span>{String(index + 1).padStart(2, "0")}</span><strong>{service}</strong></li>)}</ol></div></section>

      <section className="jtpv-professional" id="services-professionnels"><div className="jtpv-shell"><div className="jtpv-heading split"><div><p className="jtpv-eyebrow">Commercial &amp; industriel</p><h2>Des environnements exigeants.<br /><em>Des solutions structurées.</em></h2></div><p>JTPV présente une expertise destinée notamment aux bureaux, commerces, restaurants, cliniques ainsi qu’aux besoins spécialisés.</p></div><div className="jtpv-professional-grid">{jtpv.professionalGroups.map((group, index) => <article key={group.title}><span>0{index + 1}</span><div className="jtpv-service-mark" aria-hidden="true"><i /><i /></div><h3>{group.title}</h3><p>{group.text}</p></article>)}</div></div></section>

      <section className="jtpv-confidence" id="a-propos"><div className="jtpv-shell"><div className="jtpv-confidence-title"><p className="jtpv-eyebrow light">Des repères vérifiables</p><h2>Une expertise électrique<br /><em>établie.</em></h2></div><div className="jtpv-confidence-grid"><article><strong>1994</strong><h3>Une entreprise établie</h3><p>JTPV indique offrir ses services d’entrepreneur en électricité depuis 1994.</p></article><article><strong>RBQ</strong><h3>{jtpv.rbq}</h3><p>Numéro de licence publiquement répertorié pour l’entreprise.</p></article><article><strong>5 M$</strong><h3>Assurance responsabilité</h3><p>Montant d’assurance responsabilité civile annoncé par JTPV.</p></article><article><strong>24 h</strong><h3>Service d’urgence</h3><p>Le service d’urgence est affiché comme disponible 24 heures.</p></article></div><p className="jtpv-affiliation">Membre actif annoncé de la {jtpv.affiliation}.</p></div></section>

      <section className="jtpv-portfolio" id="realisations"><div className="jtpv-shell"><div className="jtpv-heading split"><div><p className="jtpv-eyebrow">Un portfolio à compléter</p><h2>Vos réalisations méritent<br />d’être <em>mieux présentées.</em></h2></div><p>Le site actuel contient encore des descriptions de projet génériques. Cette section montre comment de véritables réalisations pourraient être organisées, sans en inventer.</p></div><div className="jtpv-portfolio-grid">{jtpv.projectTypes.map((project) => <article key={project.id}><div><span>Emplacement pour une réalisation JTPV</span><b>À remplacer par un projet réel</b><i aria-hidden="true" /></div><p>Exemple de présentation</p><h3>{project.title}</h3></article>)}</div><small className="jtpv-portfolio-note">Aucun projet fictif n’est présenté comme une réalisation de JTPV.</small></div></section>

      <section className="jtpv-process"><div className="jtpv-shell"><div className="jtpv-heading"><p className="jtpv-eyebrow">Un parcours plus efficace</p><h2>Du besoin à la réalisation.</h2></div><ol>{process.map(([number, title, text]) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>

      <section className="jtpv-estimate" id="estimation"><div className="jtpv-shell jtpv-estimate-grid"><div className="jtpv-estimate-intro"><p className="jtpv-eyebrow light">Demande d’estimation</p><h2>Parlez-nous de<br /><em>votre projet.</em></h2><p>Un parcours structuré peut fournir dès le départ les informations nécessaires pour qualifier la demande.</p><aside><span>Urgence électrique 24 h</span><a href={jtpv.phone.href}>{jtpv.phone.display}</a><small>Pour une urgence, privilégiez l’appel direct.</small></aside></div><EstimateForm /></div></section>

      <section className="jtpv-digital"><div className="jtpv-shell"><div className="jtpv-heading split"><div><p className="jtpv-eyebrow">Possibilités futures</p><h2>Une expérience numérique<br />qui peut aller <em>plus loin.</em></h2></div><p>Ces pistes illustrent une évolution possible du parcours client. Elles ne sont pas présentées comme des fonctionnalités actuellement offertes par JTPV.</p></div><div className="jtpv-digital-grid">{digital.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><small>Possibilité d’évolution</small></article>)}</div></div></section>

      <section className="jtpv-faq"><div className="jtpv-shell jtpv-faq-grid"><div><p className="jtpv-eyebrow">Questions fréquentes</p><h2>Des réponses<br /><em>sous tension.</em></h2><p>Les réponses reprennent exclusivement les renseignements rendus publics par JTPV.</p></div><div>{[["Faites-vous du résidentiel?", "Oui. JTPV présente une gamme de services résidentiels couvrant notamment l’éclairage, les entrées électriques, le chauffage, la domotique et les inspections."], ["Travaillez-vous avec les entreprises?", "Oui. L’entreprise affiche des services commerciaux et industriels pour différents environnements professionnels."], ["Offrez-vous un service d’urgence?", `Oui. JTPV affiche un service d’urgence 24 h accessible au ${jtpv.phone.display}.`], ["Quelles zones desservez-vous?", "JTPV indique desservir le Grand Montréal, la Rive-Nord et la Rive-Sud."], ["Comment demander une estimation?", "Présentez votre besoin à l’aide du parcours d’estimation ou communiquez avec JTPV par téléphone." ]].map(([q,a]) => <details key={q}><summary>{q}<i /></summary><p>{a}</p></details>)}</div></div></section>

      <section className="jtpv-final"><div className="jtpv-shell"><p className="jtpv-eyebrow light">Résidentiel · Commercial · Industriel</p><h2>Un projet électrique?</h2><p>Présentez votre besoin afin de faciliter les prochaines étapes.</p><div className="jtpv-actions"><a className="jtpv-button jtpv-button-yellow" href="#estimation">Demander une estimation <span aria-hidden="true">↗</span></a><a className="jtpv-final-phone" href={jtpv.phone.href}>{jtpv.phone.display}</a></div></div></section>
    </main>

    <footer className="jtpv-footer"><div className="jtpv-shell jtpv-footer-grid"><div><Image src={jtpv.logoLight.src} alt={jtpv.logoLight.alt} width={200} height={51} /><p>Entrepreneur en électricité depuis 1994</p><p>RBQ {jtpv.rbq}</p></div><div><strong>Coordonnées</strong><a href={jtpv.phone.href}>{jtpv.phone.display}</a><address>{jtpv.address.line1}<br />{jtpv.address.line2}</address></div><div><strong>Heures affichées</strong><span>{jtpv.hours.regular}</span><span>{jtpv.hours.time}</span><b>{jtpv.hours.emergency}</b></div><div><strong>Services</strong><a href="#residentiel">Résidentiel</a><a href="#commercial">Commercial</a><a href="#industriel">Industriel</a></div><div><strong>En ligne</strong><a href={jtpv.officialWebsite} target="_blank" rel="noreferrer">Site officiel</a><a href="#estimation">Estimation</a><span>FR · Architecture prête pour EN</span></div></div><div className="jtpv-shell"><DemoFooterDisclaimer companyName="JTPV" /></div></footer>
    <JtpvMobileCta /><ScrollToTopButton />
  </div>;
}
