export const jtpv = {
  slug: "jtpv",
  companyName: "Entreprises d’Électricité J T P V Inc.",
  shortName: "JTPV",
  crmId: "PRO-2026-004",
  industry: "Électricité",
  location: "Montréal, Québec",
  since: "1994",
  phone: { display: "514-766-5878", href: "tel:+15147665878" },
  fax: "514-932-0469",
  address: { line1: "1655, rue De Sève", line2: "Montréal (Québec) H4E 2B1" },
  hours: { regular: "Lundi au vendredi", time: "7 h — 17 h", emergency: "Service d’urgence 24 h" },
  rbq: "8000-1274-54",
  liabilityInsurance: "5 M$",
  affiliation: "Corporation des maîtres électriciens du Québec",
  serviceAreas: ["Grand Montréal", "Rive-Nord", "Rive-Sud"],
  officialWebsite: "https://www.jtpv.ca/",
  logo: { src: "/jtpv/logo-concept.svg", alt: "JTPV Électricité — identité conceptuelle" },
  logoLight: { src: "/jtpv/logo-concept-light.svg", alt: "JTPV Électricité" },
  residentialServices: [
    "Éclairage, encastrés et lustres", "Prises, sorties et interrupteurs", "Éclairage d’urgence et détection", "Entrées électriques", "Chauffage et gestion énergétique", "Domotique certifiée Lutron", "Planchers radiants et câbles chauffants", "Intercoms", "Raccordements spa et piscine", "Inspections électriques",
  ],
  professionalGroups: [
    { title: "Espaces professionnels", text: "Réflexion et renouvellement pour bureaux, cliniques, restaurants et commerces." },
    { title: "Éclairage & énergie", text: "Conception d’éclairage, éclairage de vitrines et propositions d’économie d’énergie." },
    { title: "Contrôle & automatisation", text: "Contrôles, sécurité, signalisation et automatisation certifiée Lutron." },
    { title: "Données & sécurité", text: "Lignes dédiées, audio, vidéo, caméras et systèmes de détection." },
    { title: "Infrastructure électrique", text: "Installation et modification d’entrées électriques et de circuits spécialisés." },
    { title: "Maintenance & protection", text: "Maintenance préventive et protection contre les surtensions." },
  ],
  projectTypes: [
    { id: "residentiel", number: "01", title: "Résidentiel", text: "Éclairage, chauffage, entrées électriques, domotique et installations pour maisons, condos et rénovations.", image: "/jtpv/residential.jpg" },
    { id: "commercial", number: "02", title: "Commercial", text: "Solutions pour bureaux, commerces, restaurants, cliniques et autres environnements professionnels.", image: "/jtpv/commercial.jpg" },
    { id: "industriel", number: "03", title: "Industriel", text: "Infrastructure, contrôles, automatisation, maintenance et besoins électriques spécialisés.", image: "/jtpv/industrial.jpg" },
  ],
} as const;
