import type { Metadata } from "next";
import Image from "next/image";
import { DemoDisclaimerBar } from "@/components/demo/demo-disclaimer-bar";
import { DemoFooterDisclaimer } from "@/components/demo/demo-footer-disclaimer";
import { ScrollToTopButton } from "@/components/demo/scroll-to-top-button";
import { comptableDupuis } from "@/config/comptable-dupuis";
import { AppointmentForm, DupuisMobileCta, DupuisMobileMenu } from "./comptable-dupuis-client";

export const metadata: Metadata = {
  title: "Concept Gestion Comptable Dupuis — Cédric Nampa",
  description: "Proposition indépendante de modernisation de l’expérience numérique de Gestion Comptable Kathy Dupuis.",
  robots: { index: false, follow: false, nocache: true, googleBot: { index: false, follow: false, noimageindex: true } },
  openGraph: { title: "Concept Gestion Comptable Dupuis — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique de Gestion Comptable Kathy Dupuis.", url: "https://demo.cedricnampa.com/comptable-dupuis", siteName: "Démonstrations Cédric Nampa", locale: "fr_CA", type: "website", images: [{ url: "/comptable-dupuis/og.png", width: 1730, height: 909, alt: "Concept non officiel pour Gestion Comptable Kathy Dupuis" }] },
  twitter: { card: "summary_large_image", title: "Concept Gestion Comptable Dupuis — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique de Gestion Comptable Kathy Dupuis.", images: ["/comptable-dupuis/og.png"] },
};

const benefits = [
  ["25+", "Expérience", "Plus de 25 ans d’expérience en comptabilité, fiscalité et finance."],
  ["01", "Accompagnement personnalisé", "Un service adapté à la situation du particulier ou de l’entreprise."],
  ["360°", "Vision globale", "Comptabilité, fiscalité et gestion réunies dans une même approche."],
  ["Laval", "Proximité", "Un cabinet situé à Laval, au service des clients de la Rive-Nord."],
];

const process = [
  ["01", "Présentez votre situation", "Quelques informations permettent de situer votre réalité et votre demande."],
  ["02", "Analyse de vos besoins", "Le cabinet peut examiner le contexte et préciser les informations nécessaires."],
  ["03", "Recommandations adaptées", "Les options pertinentes peuvent être expliquées selon votre situation."],
  ["04", "Suivi et accompagnement", "Les prochaines étapes peuvent ensuite être organisées avec clarté."],
];

const evolutions = [
  ["01", "Dépôt sécurisé de documents", "Une future version pourrait intégrer un espace sécurisé permettant aux clients de transmettre certains documents."],
  ["02", "Rappels automatisés", "Des rappels pourraient aider à préparer les échéances et à rassembler les informations nécessaires."],
  ["03", "Suivi des demandes", "Un parcours numérique pourrait permettre aux clients de comprendre où en est leur demande."],
  ["04", "Identité numérique professionnelle", "Une modernisation pourrait harmoniser le site, les courriels professionnels et les outils numériques du cabinet."],
];

export default function ComptableDupuisPage() {
  return <div className="dupuis-site">
    <DemoDisclaimerBar companyName={comptableDupuis.companyName} />
    <a className="dupuis-skip" href="#dupuis-content">Aller au contenu</a>
    <header className="dupuis-header"><div className="dupuis-shell dupuis-header-inner"><a className="dupuis-brand" href="#accueil" aria-label="Gestion Comptable Kathy Dupuis — accueil"><Image src={comptableDupuis.logo.src} alt={comptableDupuis.logo.alt} width={190} height={68} priority /></a><nav className="dupuis-desktop-nav" aria-label="Navigation principale"><a href="#accueil">Accueil</a><a href="#particuliers">Particuliers</a><a href="#pme">PME</a><a href="#services">Services</a><a href="#a-propos">À propos</a><a href="#faq">FAQ</a><a href="#rendez-vous">Contact</a></nav><div className="dupuis-header-actions"><a className="dupuis-contact-link" href={`mailto:${comptableDupuis.email}`}>Nous contacter</a><a className="dupuis-button dupuis-header-cta" href="#rendez-vous">Prendre rendez-vous</a><DupuisMobileMenu /></div></div></header>

    <main id="dupuis-content">
      <section className="dupuis-hero dupuis-hero-background" id="accueil"><Image className="hero-background-image" src="/comptable-dupuis/hero-background.jpg" alt="Rencontre autour de documents comptables et financiers" fill priority sizes="100vw" /><div className="hero-background-shade" /><div className="dupuis-shell dupuis-hero-grid"><div className="dupuis-hero-copy"><p className="dupuis-eyebrow"><span /> Comptabilité • Fiscalité • Accompagnement</p><h1>Votre comptabilité,<br /><em>plus simple.</em><br />Vos décisions,<br /><em>mieux éclairées.</em></h1><p className="dupuis-lead">Un accompagnement comptable et fiscal pour particuliers, travailleurs autonomes et PME, avec une approche claire et adaptée à votre situation.</p><div className="dupuis-actions"><a className="dupuis-button" href="#rendez-vous">Prendre rendez-vous <span aria-hidden="true">↗</span></a><a className="dupuis-text-link" href="#parcours">Découvrir nos services <span aria-hidden="true">↓</span></a></div><p className="hero-image-source">Image d’ambiance provenant du site officiel du cabinet.</p></div></div><div className="dupuis-shell dupuis-trust"><div><strong>25+ ans</strong><span>d’expérience</span></div><div><strong>Particuliers</strong><span>services fiscaux</span></div><div><strong>Travailleurs autonomes</strong><span>comptabilité et taxes</span></div><div><strong>PME</strong><span>comptabilité et gestion</span></div></div></section>

      <section className="dupuis-section pathway-section" id="parcours"><div className="dupuis-shell"><div className="dupuis-section-title centered"><p className="dupuis-eyebrow">Deux réalités, deux parcours</p><h2>Comment pouvons-nous<br /><em>vous aider?</em></h2><p>Choisissez le profil qui correspond à votre situation pour accéder rapidement aux services pertinents.</p></div><div className="pathway-grid"><article id="particuliers"><figure className="pathway-image"><Image src="/comptable-dupuis/conseil.jpg" alt="Illustration d’une rencontre de service-conseil" fill sizes="(max-width: 760px) 100vw, 50vw" /><figcaption>Service-conseil</figcaption></figure><div className="pathway-content"><div className="pathway-head"><span>01</span><p>Je suis un</p><h3>Particulier</h3></div><p>Un accompagnement pour simplifier vos obligations fiscales et certaines situations personnelles.</p><ul>{comptableDupuis.individuals.slice(1).map((service) => <li key={service}>{service}</li>)}</ul><a className="dupuis-button dupuis-button-light" href="#services">Voir les services particuliers <span aria-hidden="true">↗</span></a></div></article><article id="pme"><figure className="pathway-image"><Image src="/comptable-dupuis/analyse.jpg" alt="Illustration d’un travail d’analyse financière sur ordinateur" fill sizes="(max-width: 760px) 100vw, 50vw" /><figcaption>Analyse &amp; gestion</figcaption></figure><div className="pathway-content"><div className="pathway-head"><span>02</span><p>Je suis entrepreneur ou</p><h3>PME</h3></div><p>Une expertise comptable, fiscale et financière pour accompagner les réalités de l’entreprise.</p><ul>{comptableDupuis.businesses.slice(0,7).map((service) => <li key={service}>{service}</li>)}</ul><a className="dupuis-button dupuis-button-sage" href="#services">Voir les services aux entreprises <span aria-hidden="true">↗</span></a></div></article></div><p className="dupuis-image-note">Images d’ambiance issues du site officiel de Gestion Comptable Kathy Dupuis.</p></div></section>

      <section className="dupuis-section services-catalog" id="services"><div className="dupuis-shell"><div className="dupuis-section-title split"><div><p className="dupuis-eyebrow">Une offre mieux organisée</p><h2>L’essentiel,<br />au bon endroit.</h2></div><p>Plutôt que de présenter chaque service avec le même poids, cette proposition regroupe l’expertise du cabinet en quatre familles faciles à parcourir.</p></div><div className="service-groups">{comptableDupuis.serviceGroups.map((group) => <article key={group.number}><div className="group-number">{group.number}</div><div><h3>{group.title}</h3><p>{group.description}</p><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}</div></div></section>

      <section className="dupuis-section expertise-section" id="a-propos"><div className="dupuis-shell expertise-grid"><div className="expertise-intro"><p className="dupuis-eyebrow light">Pourquoi nous consulter</p><h2>Une expertise qui va<br /><em>au-delà des chiffres.</em></h2><p>La comptabilité devient plus utile lorsqu’elle aide aussi à comprendre une situation, à respecter ses obligations et à mieux préparer les prochaines décisions.</p><a className="dupuis-button dupuis-button-cream" href="#rendez-vous">Présenter votre situation <span aria-hidden="true">↗</span></a></div><div className="expertise-benefits">{benefits.map(([value,title,text]) => <article key={title}><strong>{value}</strong><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

      <section className="dupuis-section process-section-dupuis"><div className="dupuis-shell"><div className="dupuis-section-title split"><div><p className="dupuis-eyebrow">Une démarche structurée</p><h2>Un accompagnement simple,<br />étape par étape.</h2></div><p>Un parcours clair aide à préparer le premier échange et à orienter chaque demande vers le bon service.</p></div><ol className="dupuis-process">{process.map(([number,title,text]) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>

      <section className="dupuis-section appointment-section" id="rendez-vous"><div className="dupuis-shell appointment-grid"><div className="appointment-intro"><p className="dupuis-eyebrow light">Prise de rendez-vous</p><h2>Parlez-nous de<br /><em>votre besoin.</em></h2><p>Quelques informations permettent de mieux comprendre votre situation et de préparer un premier échange plus pertinent.</p><div className="appointment-contact"><span>Vous préférez nous joindre directement?</span><a href={comptableDupuis.phone.href}>{comptableDupuis.phone.display}</a><a href={`mailto:${comptableDupuis.email}`}>{comptableDupuis.email}</a></div><div className="qualification-note"><strong>Une demande mieux qualifiée</strong><p>Ce parcours pourrait réduire les échanges préliminaires et diriger plus rapidement chaque personne vers le service approprié.</p></div></div><AppointmentForm /></div></section>

      <section className="dupuis-section evolution-section"><div className="dupuis-shell"><div className="dupuis-section-title split"><div><p className="dupuis-eyebrow">Possibilités d’évolution</p><h2>Une expérience client qui pourrait aller <em>encore plus loin.</em></h2></div><p>Une future modernisation pourrait relier le site à des outils simples qui facilitent les échanges et l’organisation du cabinet.</p></div><div className="evolution-grid">{evolutions.map(([number,title,text]) => <article key={number}><span>{number}</span><div className="evolution-icon" aria-hidden="true"><i /><i /></div><h3>{title}</h3><p>{text}</p><small>Possibilité future — non disponible dans cette démo</small></article>)}</div></div></section>

      <section className="trust-section"><div className="dupuis-shell"><div className="trust-panel"><div className="trust-panel-heading"><p className="dupuis-eyebrow light"><span /> Une relation basée sur la confiance</p><h2>Des situations différentes.<br /><em>Une écoute attentive.</em></h2></div><div className="trust-panel-copy"><p>Particulier, travailleur autonome ou dirigeant de PME : chaque dossier possède son propre contexte. L’approche présentée par le cabinet met de l’avant un service professionnel, adapté aux besoins et traité avec discrétion.</p><ul aria-label="Principes de l’accompagnement"><li><span>01</span> Écoute</li><li><span>02</span> Discrétion</li><li><span>03</span> Clarté</li></ul></div><i className="trust-panel-mark" aria-hidden="true">KD</i></div></div></section>

      <section className="dupuis-section dupuis-faq" id="faq"><div className="dupuis-shell faq-grid-dupuis"><div><p className="dupuis-eyebrow">Questions fréquentes</p><h2>Quelques réponses<br />pour vous orienter.</h2><p>Les informations suivantes reprennent uniquement les services présentés publiquement par le cabinet.</p></div><div className="faq-list-dupuis"><details><summary>Travaillez-vous avec les particuliers?<i /></summary><p>Oui. Le cabinet présente notamment des services d’impôt personnel, de revenus locatifs, de succession, de conformité pour non-résidents et de service-conseil.</p></details><details><summary>Accompagnez-vous les PME?<i /></summary><p>Oui. Les services publiés couvrent notamment la tenue de livres, la paie, les documents gouvernementaux, la fiscalité, les informations financières, le démarrage et l’analyse financière.</p></details><details><summary>Offrez-vous des services aux travailleurs autonomes?<i /></summary><p>Oui. Le cabinet indique pouvoir compiler les données, produire les déclarations de revenus et, lorsqu’applicable, les rapports TPS et TVQ.</p></details><details><summary>Quels types de services comptables proposez-vous?<i /></summary><p>L’offre couvre la comptabilité courante, la fiscalité personnelle et d’entreprise, certaines situations particulières et l’accompagnement financier des PME.</p></details><details><summary>Comment prendre rendez-vous?<i /></summary><p>Vous pouvez utiliser le parcours de demande présenté ici ou joindre le cabinet par téléphone ou par courriel à partir des coordonnées publiques.</p></details></div></div></section>

      <section className="dupuis-final-cta"><div className="dupuis-shell"><div><p className="dupuis-eyebrow light">Votre situation mérite une réponse claire</p><h2>Besoin d’un accompagnement<br />comptable ou fiscal?</h2><p>Présentez-nous brièvement votre situation afin d’identifier le service le plus adapté à vos besoins.</p></div><div className="dupuis-actions"><a className="dupuis-button dupuis-button-cream" href="#rendez-vous">Prendre rendez-vous <span aria-hidden="true">↗</span></a><a className="dupuis-outline-link" href="#services">Voir les services</a></div></div></section>

      <section className="dupuis-location" aria-labelledby="dupuis-location-title"><div className="dupuis-location-map"><iframe src={comptableDupuis.address.mapEmbed} title="Carte indiquant l’emplacement de Gestion Comptable Kathy Dupuis à Laval" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><div className="dupuis-shell dupuis-location-shell"><div className="dupuis-location-card"><p className="dupuis-eyebrow"><span /> Nous trouver</p><h2 id="dupuis-location-title">Au cœur de<br /><em>Laval.</em></h2><address>{comptableDupuis.address.line1}<br />{comptableDupuis.address.line2}</address><a className="dupuis-button" href={comptableDupuis.address.directions} target="_blank" rel="noreferrer">Obtenir l’itinéraire <span aria-hidden="true">↗</span></a></div></div></section>
    </main>

    <footer className="dupuis-footer" id="contact"><div className="dupuis-shell dupuis-footer-grid"><div><Image src={comptableDupuis.logo.src} alt={comptableDupuis.logo.alt} width={210} height={75} /><p>Comptabilité · Fiscalité · Accompagnement</p><p>{comptableDupuis.experience}</p></div><div><strong>Coordonnées</strong><a href={comptableDupuis.phone.href}>{comptableDupuis.phone.display}</a><a href={`mailto:${comptableDupuis.email}`}>{comptableDupuis.email}</a><address>{comptableDupuis.address.line1}<br />{comptableDupuis.address.line2}</address></div><div><strong>Parcours</strong><a href="#particuliers">Particuliers</a><a href="#pme">Entrepreneurs et PME</a><a href="#rendez-vous">Prendre rendez-vous</a></div><div><strong>En ligne</strong><a href={comptableDupuis.officialWebsite}>Site officiel</a><span>{comptableDupuis.location}</span></div></div><div className="dupuis-shell"><DemoFooterDisclaimer companyName={comptableDupuis.companyName} /></div></footer>
    <DupuisMobileCta />
    <ScrollToTopButton />
  </div>;
}
