import type { Metadata } from "next";
import Image from "next/image";
import { DemoDisclaimerBar } from "@/components/demo/demo-disclaimer-bar";
import { DemoFooterDisclaimer } from "@/components/demo/demo-footer-disclaimer";
import { ScrollToTopButton } from "@/components/demo/scroll-to-top-button";
import { aubierCpa } from "@/config/aubier-cpa";
import { AubierContactForm, AubierMobileCta, AubierMobileMenu } from "./aubier-cpa-client";

export const metadata: Metadata = {
  title: "Concept Aubier CPA — Cédric Nampa",
  description: "Proposition indépendante de modernisation de l’expérience numérique d’Aubier CPA.",
  robots: { index: false, follow: false, nocache: true, googleBot: { index: false, follow: false, noimageindex: true } },
  openGraph: { title: "Concept Aubier CPA — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique d’Aubier CPA.", url: "https://demo.cedricnampa.com/aubier-cpa", siteName: "Démonstrations Cédric Nampa", locale: "fr_CA", type: "website", images: [{ url: "/aubier-cpa/og.svg", width: 1200, height: 630, alt: "Concept non officiel de modernisation numérique pour Aubier CPA" }] },
  twitter: { card: "summary_large_image", title: "Concept Aubier CPA — Cédric Nampa", description: "Proposition indépendante de modernisation de l’expérience numérique d’Aubier CPA.", images: ["/aubier-cpa/og.svg"] },
};

const businessStages = ["Démarrage", "Croissance", "Fiscalité", "Gestion", "Acquisition / Vente"];
const possibilities = [
  ["01", "Routage intelligent des demandes", "Une demande pourrait être dirigée vers le bureau ou le professionnel approprié selon le besoin sélectionné."],
  ["02", "Collecte sécurisée de documents", "Une future évolution pourrait intégrer une solution sécurisée adaptée aux échanges de documents du cabinet."],
  ["03", "Prise de rendez-vous", "Le parcours pourrait être connecté à un calendrier afin de simplifier la planification d’un premier échange."],
  ["04", "Automatisation des suivis", "Confirmations et rappels pourraient être déclenchés automatiquement après une demande."],
];

export default function AubierCpaPage() {
  return <div className="aubier-site">
    <DemoDisclaimerBar companyName={aubierCpa.companyName} detailText="Cette page est un concept indépendant réalisé à des fins de démonstration et de prospection. Elle ne représente pas le site officiel d’Aubier CPA, n’a pas été commandée par le cabinet et n’implique aucune collaboration ou approbation de sa part." />
    <a className="aubier-skip" href="#aubier-content">Aller au contenu</a>
    <header className="aubier-header"><div className="aubier-shell aubier-header-inner"><a className="aubier-brand" href="#accueil" aria-label="Aubier CPA — accueil"><Image src={aubierCpa.logo.src} alt={aubierCpa.logo.alt} width={180} height={58} priority /></a><nav className="aubier-desktop-nav" aria-label="Navigation principale"><a href="#expertise">Expertise</a><a href="#services">Services</a><a href="#entreprises">Entreprises</a><a href="#equipe">Notre équipe</a><a href="#bureaux">Nos bureaux</a><a href="#contact">Nous joindre</a></nav><a className="aubier-button aubier-header-cta" href="#contact">Prendre rendez-vous</a><AubierMobileMenu /></div></header>

    <main id="aubier-content">
      <section className="aubier-hero" id="accueil"><div className="aubier-hero-image"><Image src="/aubier-cpa/hero.jpg" alt="Échange professionnel dans un bureau" fill priority sizes="100vw" /><div /></div><div className="aubier-shell aubier-hero-content"><p className="aubier-kicker light"><span /> Comptabilité · Fiscalité · Conseil</p><h1>Des chiffres maîtrisés.<br /><em>Des décisions mieux éclairées.</em></h1><p>Aubier CPA accompagne les entreprises, entrepreneurs, fiducies et particuliers en affaires dans leurs enjeux comptables, fiscaux et stratégiques.</p><div className="aubier-actions"><a className="aubier-button aubier-button-light" href="#contact">Parler à un professionnel <span aria-hidden="true">↗</span></a><a className="aubier-text-link light" href="#services">Explorer nos services <span aria-hidden="true">↓</span></a></div></div><div className="aubier-shell aubier-hero-trust"><div><strong>Depuis 1993</strong><span>Une expertise auprès des PME</span></div><div><strong>4 implantations</strong><span>Québec, Beauport et Baie-Saint-Paul</span></div><div><strong>CPA &amp; fiscalistes</strong><span>Une équipe multidisciplinaire</span></div></div></section>

      <section className="aubier-needs" id="services"><div className="aubier-shell"><div className="aubier-heading aubier-heading-split"><div><p className="aubier-kicker">Une navigation pensée autrement</p><h2>Comment pouvons-nous<br /><em>vous accompagner?</em></h2></div><p>Partez de votre situation plutôt que d’un terme technique. Chaque parcours rassemble les expertises qui peuvent contribuer à votre prochain pas.</p></div><div className="aubier-needs-grid">{aubierCpa.needs.map((need, index) => <article key={need.number} className={index === 0 ? "featured" : ""}><span>{need.number}</span><h3>{need.title}</h3><p>{need.text}</p><ul>{need.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul><a href="#expertise">Découvrir <span aria-hidden="true">↗</span></a></article>)}</div></div></section>

      <section className="aubier-expertise" id="expertise"><div className="aubier-shell"><div className="aubier-heading centered"><p className="aubier-kicker light">Une gamme complète, plus simple à parcourir</p><h2>Une expertise qui accompagne<br /><em>chaque étape.</em></h2></div><div className="aubier-expertise-list">{aubierCpa.expertise.map((item, index) => <article key={item.title}><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

      <section className="aubier-business" id="entreprises"><div className="aubier-business-photo"><Image src="/aubier-cpa/hero.jpg" alt="Rencontre d’affaires dans un environnement professionnel" fill sizes="(max-width: 850px) 100vw, 48vw" /></div><div className="aubier-business-copy"><p className="aubier-kicker">Au service des PME depuis 1993</p><h2>Vous développez<br />votre entreprise.<br /><em>Voyons plus loin.</em></h2><p>Au-delà des obligations comptables, les services publiés par Aubier couvrent aussi l’analyse, le financement de projets, la fiscalité, le redressement et le conseil stratégique.</p><div className="aubier-stage-list">{businessStages.map((stage, index) => <span key={stage}><i>0{index + 1}</i>{stage}</span>)}</div><a className="aubier-button" href="#expertise">Découvrir l’expertise entreprise <span aria-hidden="true">↗</span></a></div></section>

      <section className="aubier-history"><div className="aubier-shell aubier-history-grid"><div><p className="aubier-kicker light">Une expertise construite dans le temps</p><strong>1993</strong><span aria-hidden="true">→</span><strong>Aujourd’hui</strong></div><div><h2>Une connaissance approfondie<br />des réalités de la PME.</h2><p>Depuis 1993, Aubier CPA indique avoir développé son expertise dans les domaines de la comptabilité, de la gestion et de la fiscalité auprès des PME.</p></div></div></section>

      <section className="aubier-team" id="equipe"><div className="aubier-shell"><div className="aubier-heading aubier-heading-split"><div><p className="aubier-kicker">L’expertise est aussi humaine</p><h2>Des professionnels derrière<br /><em>chaque décision.</em></h2></div><p>CPA, fiscalistes et professionnels expérimentés accompagnent les dossiers selon leur nature et leur complexité.</p></div><div className="aubier-team-grid">{aubierCpa.team.map((member, index) => <article key={member.name}><figure><Image src={member.image} alt={member.name} fill sizes="(max-width: 700px) 100vw, 33vw" /></figure><div><span>0{index + 1}</span><h3>{member.name}</h3><p>{member.title}</p></div></article>)}<aside><p className="aubier-kicker light">Une équipe multidisciplinaire</p><h3>Le bon regard,<br />au bon moment.</h3><p>La composition publique du cabinet réunit notamment des CPA, fiscalistes et techniciennes comptables.</p><a href="https://www.aubiercpa.ca/equipe/" target="_blank" rel="noreferrer">Voir l’équipe officielle <span aria-hidden="true">↗</span></a></aside></div></div></section>

      <section className="aubier-offices" id="bureaux"><div className="aubier-shell"><div className="aubier-heading aubier-heading-split"><div><p className="aubier-kicker">Quatre implantations confirmées</p><h2>Une expertise<br /><em>proche de vous.</em></h2></div><p>Choisissez le bureau le plus approprié à votre situation. Les coordonnées suivantes proviennent du site officiel d’Aubier CPA.</p></div><div className="aubier-office-grid">{aubierCpa.offices.map((office, index) => <article key={office.name}><span>0{index + 1}</span><h3>{office.name}</h3><address>{office.address}<br />{office.city}</address><a href={office.href}>{office.phone}</a></article>)}</div></div></section>

      <section className="aubier-contact" id="contact"><div className="aubier-shell aubier-contact-grid"><div className="aubier-contact-intro"><p className="aubier-kicker light">Une demande mieux orientée</p><h2>Parlez-nous de<br /><em>votre situation.</em></h2><p>Quelques informations peuvent permettre de diriger la demande vers le bon bureau ou la bonne expertise dès le premier échange.</p><div><span>Coordonnées publiques</span><a href={aubierCpa.phone.href}>{aubierCpa.phone.display}</a><a href={`mailto:${aubierCpa.email}`}>{aubierCpa.email}</a></div></div><AubierContactForm /></div></section>

      <section className="aubier-digital"><div className="aubier-shell"><div className="aubier-heading aubier-heading-split"><div><p className="aubier-kicker">Possibilités d’évolution</p><h2>Une expérience numérique<br />qui peut aller <em>plus loin.</em></h2></div><p>Ces pistes illustrent des possibilités futures. Elles ne sont pas présentées comme des fonctionnalités actuellement offertes par Aubier CPA.</p></div><div className="aubier-digital-grid">{possibilities.map(([number, title, text]) => <article key={number}><span>{number}</span><div aria-hidden="true"><i /><i /></div><h3>{title}</h3><p>{text}</p><small>Possibilité future</small></article>)}</div></div></section>

      <section className="aubier-insights"><div className="aubier-shell"><div className="aubier-heading aubier-heading-split"><div><p className="aubier-kicker">Contenu public du cabinet</p><h2>Actualités &amp;<br /><em>perspectives.</em></h2></div><a className="aubier-text-link" href="https://www.aubiercpa.ca/conseils-comptable-quebec/" target="_blank" rel="noreferrer">Consulter les conseils officiels <span aria-hidden="true">↗</span></a></div><div className="aubier-insights-grid">{aubierCpa.insights.map((insight, index) => <article key={insight.title}><span>{insight.category}</span><strong>0{index + 1}</strong><h3>{insight.title}</h3><p>{insight.text}</p><a href={aubierCpa.officialWebsite} target="_blank" rel="noreferrer">Lire sur le site officiel <span aria-hidden="true">↗</span></a></article>)}</div></div></section>

      <section className="aubier-faq"><div className="aubier-shell aubier-faq-grid"><div><p className="aubier-kicker">Questions fréquentes</p><h2>Pour mieux<br /><em>vous orienter.</em></h2></div><div>{[
        ["Quels services propose Aubier CPA?", "Le cabinet présente des services de certification, comptabilité, fiscalité, tenue de registres, gestion immobilière, succession, analyse financière, démarrage, redressement et conseil stratégique."],
        ["Accompagnez-vous les PME?", "Oui. Aubier CPA indique avoir développé depuis 1993 une expertise auprès des PME en comptabilité, gestion et fiscalité."],
        ["Où sont situés vos bureaux?", "Les quatre implantations affichées sont Sainte-Foy, Promenades Beauport, Aubier Comptabilité et Impôts à Beauport, et Baie-Saint-Paul."],
        ["Offrez-vous des services aux particuliers?", "Oui. Le cabinet publie notamment des services de déclarations personnelles et de planification fiscale et successorale pour les particuliers."],
        ["Comment prendre rendez-vous?", `Le cabinet peut être joint au ${aubierCpa.phone.display}, par courriel ou à partir de ses coordonnées officielles.`],
      ].map(([question, answer]) => <details key={question}><summary>{question}<i /></summary><p>{answer}</p></details>)}</div></div></section>

      <section className="aubier-final"><div className="aubier-shell"><p className="aubier-kicker light">Le premier échange commence ici</p><h2>Parlons de vos projets.</h2><p>Comptabilité, fiscalité ou accompagnement d’affaires : commencez par nous présenter votre situation.</p><div className="aubier-actions"><a className="aubier-button aubier-button-light" href="#contact">Prendre rendez-vous <span aria-hidden="true">↗</span></a><a className="aubier-text-link light" href="#bureaux">Trouver un bureau <span aria-hidden="true">↓</span></a></div></div></section>
    </main>

    <footer className="aubier-footer"><div className="aubier-shell aubier-footer-grid"><div><Image src={aubierCpa.logo.src} alt={aubierCpa.logo.alt} width={190} height={61} /><p>Comptabilité · Fiscalité · Conseil</p><a href={aubierCpa.phone.href}>{aubierCpa.phone.display}</a><a href={`mailto:${aubierCpa.email}`}>{aubierCpa.email}</a></div><div><strong>Expertise</strong><a href="#expertise">Comptabilité &amp; certification</a><a href="#expertise">Fiscalité</a><a href="#expertise">Gestion &amp; stratégie</a></div><div><strong>Clientèles</strong><a href="#entreprises">Entreprises &amp; PME</a><a href="#services">Particuliers en affaires</a><a href="#services">Fiducies</a></div><div><strong>Bureaux</strong>{aubierCpa.offices.map((office) => <a href="#bureaux" key={office.name}>{office.name.replace("Aubier CPA — ", "").replace("Aubier Comptabilité et Impôts — ", "")}</a>)}</div><div><strong>En ligne</strong><a href={aubierCpa.officialWebsite} target="_blank" rel="noreferrer">Site officiel</a><a href="#contact">Prendre rendez-vous</a></div></div><div className="aubier-shell"><DemoFooterDisclaimer companyName={aubierCpa.companyName} /></div></footer>
    <AubierMobileCta /><ScrollToTopButton />
  </div>;
}
